apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: o5nvkm2u9-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/o5nvkm2u9-dotnet-basic-gitops